// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyntffvtcvfpzfxdnhfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bnRmZnZ0Y3ZmcHpmeGRuaGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0ODc0MDIsImV4cCI6MjA4NjA2MzQwMn0.GiJ-nbuq2oU3ZcCacRRDl6fQ5NDPnmI6aVlMKI27Wvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});